version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pgdocker
      POSTGRES_PASSWORD: pgdocker
    ports:
      - 5432:5432
    networks:
      - postgres-network

  adminer:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgdocker@pgdocker.com"
      PGADMIN_DEFAULT_PASSWORD: "pgdocker"
    ports:
      - 16543:80
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge